<?php

declare(strict_types=1);

namespace Prism\Core\Commands;

use LaravelZero\Framework\Commands\Command;
use Symfony\Component\Process\Process;

use function base_path;

class BuildCommand extends Command
{
    /**
     * The signature of the command.
     *
     * @var string
     */
    protected $signature = 'build {env=local : Target environment (e.g. local, production)}';

    /**
     * The description of the command.
     *
     * @var string
     */
    protected $description = 'Run the Prism static site build using Jigsaw.';

    public function handle(): int
    {
        $environment = (string) $this->argument('env');
        $workingDirectory = getcwd() ?: base_path();

        $sourcePath = $workingDirectory . DIRECTORY_SEPARATOR . 'source';
        if (! is_dir($sourcePath)) {
            $this->error("Missing source directory at {$sourcePath}. Ensure you run this from the client root.");

            return self::FAILURE;
        }

        $scriptToUse = $this->findJigsawBinary($workingDirectory);

        if (! $scriptToUse) {
            return self::FAILURE;
        }

        $bootstrapPath = $workingDirectory . DIRECTORY_SEPARATOR . 'bootstrap.php';
        $tempBootstrapCreated = false;

        if (! file_exists($bootstrapPath)) {
            $this->info("Zero-config: Injecting Prism engine listeners...");
            file_put_contents($bootstrapPath, $this->getBootstrapStub());
            $tempBootstrapCreated = true;
        }

        $this->info("Building static site (env: {$environment}) from {$workingDirectory}");

        try {
            $exitCode = $this->runJigsaw($scriptToUse, $environment, $workingDirectory);
        } finally {
            if ($tempBootstrapCreated && file_exists($bootstrapPath)) {
                unlink($bootstrapPath);
            }
        }

        if ($exitCode !== 0) {
            $this->error('Jigsaw build failed.');

            return self::FAILURE;
        }

        $this->info('Jigsaw build completed.');

        return self::SUCCESS;
    }

    protected function findJigsawBinary(string $workingDirectory): ?string
    {
        $possiblePaths = [
            $workingDirectory . '/vendor/tightenco/jigsaw/jigsaw',
            $workingDirectory . '/vendor/bin/jigsaw',
            base_path('vendor/tightenco/jigsaw/jigsaw'),
            base_path('vendor/bin/jigsaw'),
        ];

        foreach ($possiblePaths as $path) {
            if (is_file($path)) {
                return $path;
            }
        }

        $this->error("Jigsaw binary not found. searched in:\n" . implode("\n", $possiblePaths));
        $this->error("Ensure you run this from the client root and `composer require tightenco/jigsaw` is installed.");

        return null;
    }

    protected function runJigsaw(string $scriptToUse, string $environment, string $workingDirectory): int
    {
        $command = [
            PHP_BINARY,
            '-d',
            'auto_prepend_file=' . base_path('vendor/autoload.php'),
            $scriptToUse,
            'build',
            $environment,
        ];

        $process = new Process($command, $workingDirectory, [
            'JIGSAW_BASE' => $workingDirectory,
        ]);

        $process->run(function ($type, $buffer): void {
            $type === Process::ERR ? $this->error(trim($buffer)) : $this->line(trim($buffer));
        });

        return (int) $process->getExitCode();
    }

    protected function getBootstrapStub(): string
    {
        return <<<'PHP'
<?php

/**
 * Prism Core Bridge
 * This file was automatically generated by the Prism CLI to enable 
 * core engine features in a thin-client environment.
 */

/** @var \TightenCo\Jigsaw\Events\EventBus $events */
$events->beforeBuild(\Prism\Core\Listeners\TemplateLoader::class);

PHP;
    }
}